### ISSUE TITLE
In some editions of Windows using non UTF-8, displaying DiagnosticRecord causes thread 'main' panicked at 'called `Result::unwrap()` on Utf8Error

### ISSUE THREAD

**Issue by xyx-is** [Koka/odbc-rs#103]
I'm using a Japanese edition of Windows and MSSQL. When I call `env.connect_with_connection_string` with an incorrect connection string, the function does not return an `Err`, but causes following panick with `Utf8Error`.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 33, error_len: Some(1) }', libcore\result.rs:1009:5
stack backtrace:
...
  12: odbc::diagnostics::{{impl}}::fmt
             at C:\Users\username\Project\rust\odbc_test\odbc-rs\src\diagnostics.rs:63
...
  21: env_logger::fmt::DefaultFormat::write_args
             at C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\env_logger-0.6.0\src\fmt\mod.rs:290
...
  28: log::__private_api_log
             at C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\log-0.4.6\src\lib.rs:1232
  29: odbc::result::into_result<odbc_safe::data_source::DataSource<odbc_safe::data_source::connected::Connected>,odbc_safe::data_source::DataSource<odbc_safe::data_source::unconnected::Unconnected>>
             at C:\Users\username\Project\rust\odbc_test\odbc-rs\src\result.rs:95
  30: odbc::environment::Environment<odbc_safe::version::Odbc3>::connect_with_connection_string
             at C:\Users\username\Project\rust\odbc_test\odbc-rs\src\connection.rs:40
...
  41: main
...
error: process didn't exit successfully: `target\debug\odbc_test.exe` (exit code: 101)
```

This is because the ODBC driver returns messages in Shift_JIS (strictly speaking, it is Windows-31J) encoding, which is incompatible with UTF-8. As an experiment, I have rewrited using encoding_rs 0.8.15 odbc-rs/src/diagnostics.rs:63 as follows.

https://github.com/Koka/odbc-rs/blob/3e8d207826273d4f91e9b388123f853acd7ce504/src/diagnostics.rs#L63

```
            encoding_rs::SHIFT_JIS.decode(message.to_bytes()).0
```

This rewriting passes `connect_with_connection_string` and the function returns `Err` correctly. The following message is the proper message in Shift_JIS, which causes Utf8Error panick above.

```
[2019-02-07T11:25:39Z ERROR odbc::result] State: IM002, Native error: 0, Message: [Microsoft][ODBC Driver Manager] デー タ ソース名および指定された既定のドライバーが見つかりません。
```
(FYI, this message says "The data source name and specified default driver is not found" in Japanese.)

Of course this rewriting is just an experimental code and can never be accepted as production code. I'm new to Rust and ODBC, but I think it is better to create some mechanisms to provide some way for users to change the conversion from `std::ffi::CStr` to string.

Note: This problem seems to be common in CJK editions of Windows.
* Japanese editions of Windows use Microsoft Code Page 932 (Windows-31J, or called Shift_JIS inaccurately) by default
* Simplified Chinese editions of Windows use Microsoft Code Page 936 (GBK) by default
* Korean editions of Windows use Microsoft Code Page 949 (UCH) by default

The default code page can surely be changed, but there are hardly any users change the setting, and even some CJK applications assume that the setting is not changed.

This problem is similar to #94, #52, #86.

**Comment by Koka** [comment]
Thanks for your feedback! Yes, this part of library definitely need some polishing especially related to non-unicode support. Unfortunately I unlikely will have free time to fix this in the near future, but you're always welcome to post pull request with fixes.

**Comment by xyx-is** [comment]
Thank you for your reply. Do you have any ideas to improve DiagnosticRecord to provide some way for users to change the conversion from `std::ffi::CStr` to string?
If you could suggest some Rust design patterns or implementation directions, I might try it if i could.

**Comment by yuana1** [comment]
@xyx-is , you can try https://github.com/yuana1/odbc-rs,
toml like this
![image](https://user-images.githubusercontent.com/7308509/52680773-adcb3b80-2f74-11e9-9926-d3a9518e85b7.png)

just replace 
```
    // equal to create_environment_v3("UTF-8", "UTF-8").unwrap();
    let env = create_environment_v3().unwrap();
```
to
```
    // The first parameter is os_encoding, and the second parameter is db_encoding.
    let env = create_environment_v3_with_os_db_encoding("GB18030", "GB18030").unwrap();
```
GB18030 is chinese encoding, and  you may need to replace it with "SHIFT_JIS".
I tested it in chinese, and it worked.

**Comment by yuana1** [comment]
@xyx-is  example 
https://gist.github.com/yuana1/b9f5785dd4afdd85f78d11d97b55489e

**Comment by xyx-is** [comment]
@yuana1 Thank you. This patch is greatly helpful.

**Comment by bbigras** [comment]
@yuana1 Any plans to merge this patch?

**Comment by Koka** [comment]
@yuana1 I took it upon myself to create a pull request https://github.com/Koka/odbc-rs/pull/115 which integrates your changes to the master branch. Anyway I would like to have your permission as original changeset author to merge this in.

**Comment by Koka** [comment]
I guess we can merge this, as @yuana1 is silent
