### ISSUE TITLE
cannot use tables / tables_str with mariadb-driver because it needs NULL

### ISSUE THREAD

**Issue by aligator** [Koka/odbc-rs#110]
I tried to use tables_str to get all tables from a maria db.

It always returns an empty result. After some trying with odbc-c-binding and calling SQLTables with odbc-sys directly I found the solution.
If I passs null_mut() to SQLTables for catalog, schema and table, it works. So there has to be a way for tables / tables_str to provide null. Maybe with an Optional?

Don't know why the mariadb-driver handles this differently than other drivers (tried sqlite, which works if I use "%"-strings)

**Comment by Koka** [comment]
Closing this as  #111 was merged
