### ISSUE TITLE
Panic if LANG env variable isn't set.

### ISSUE THREAD

**Issue by cetra3** [Koka/odbc-rs#117]
I'm seeing a panic using odbc if the `LANG` environment variable isn't set:

```
thread 'main' panicked at 'not yet implemented', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/odbc-0.14.0/src/statement/types.rs:176:31
```

This relates to the [following portion](https://github.com/Koka/odbc-rs/blob/77af3cd03ba5bc673b8d23676ec1fa8695e8e625/src/statement/types.rs#L176) of code:

```rust
    fn convert(buffer: &'a [u8]) -> Self {
        let cow = unsafe { ::environment::DB_ENCODING }.decode(buffer).0;
        match cow {
            Borrowed(strref) => strref,
            Owned(_string) => unimplemented!(),
        }
    }
```

If I set `LANG=en_US.UTF-8` this doesn't appear to trigger the unimplemented branch.   Happy to submit a PR to implement it, but I'm not exactly sure what needs to happen in this case.

**Comment by Koka** [comment]
Thanks for your question.

This code branch was intentionally left unimplemented because there are no easy way to return an owned value as reference.  

Could you please show the code which leads to this error? May be it could be rewritten to use Cow or String variant of convert function?

And I guess if we may be should use more meaningful panic message here instead of unimplemented!

**Comment by cetra3** [comment]
It'd be hard to reduce this down, but I think it relates to this bit of code:

```
cursor.get_data::<&str>(idx)
```

I am assuming it's because the language env not being set means that encode_rs doesn't do a passthrough and instead has to create an owned version to convert it.  It looks like my code does a conversion to an owned string after this statement, so I can probably just `get_data` straight to `String`

Regardless: it is a tiny bit obscure when you see this panic!

**Comment by cfsamson** [comment]
A better error message would indeed be very helpful though. 

I used this crate to connect using IBM iseries Access ODBC Driver and setting a `LANG` environment variable didn't help but changing from `cursor.get_data::<&str>(i as u16)?` to `cursor.get_data::<String>(i as u16)?` worked which was an easy workaround when I read this issue and figured out what was going on. This would also imply that a missing `LANG` env variable is not the only case in which an `encode_rs` needs to create an owned value.

**Comment by Koka** [comment]
@cfsamson Thanks for your comment, unfortunately I have very small amount of time to maintain this crate recently, but I'll gladly accept any useful PR on this subject.

**Comment by cfsamson** [comment]
@Koka Of course, no problem. I made a PR now so have a look at it when you have some time.
