### ISSUE TITLE
OSX Build Error, Unable to link with cc

### ISSUE THREAD

**Issue by jrsmith17** [Koka/odbc-rs#122]
I was trying to evaluate the ODBC crate for a connection to Snowflake. This is behind a corporate firewall, so I've modified the path in the error message to not report sensitive info.

`$ cargo run
   Compiling <project> v0.1.0 (/Users/<my_user>/<project>)
error: linking with cc failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/<my_user>/<project>/target/debug/deps/<project>-e6f4733065e2a602.1qkl8d8wrzock9kb.rcgu.o" "/Users/<my_user>/<project>/target/debug/deps/<project>-e6f4733065e2a602.3matjfnoj00r44h0.rcgu.o" "/Users/<my_user>/<project>/target/debug/deps/<project>-e6f4733065e2a602.3ubgblp7dup27l4d.rcgu.o" "/Users/<my_user>/<project>/target/debug/deps/<project>-e6f4733065e2a602.4m8v4wwyq571naim.rcgu.o" "/Users/<my_user>/<project>/target/debug/deps/<project>-e6f4733065e2a602.5sji8ezxrldtah5.rcgu.o" "-o" "/Users/<my_user>/<project>/target/debug/deps/<project>-e6f4733065e2a602" "/Users/<my_user>/<project>/target/debug/deps/<project>-e6f4733065e2a602.5d0nec8rtamh45mt.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/<my_user>/<project>/target/debug/deps" "-L" "/Users/<my_user>/<project>/target/debug/build/backtrace-sys-a847bb58001c105f/out" "-L" "/Users/<my_user>/<project>/target/debug/build/brotli-sys-b7227223821e7c65/out" "-L" "/Users/<my_user>/<project>/target/debug/build/miniz-sys-004c205c1662ced2/out" "-L" "/Users/<my_user>/Downloads/ImageMagick-7.0.8/lib/" "-L" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib" "-L" "/Users/<my_user>/<project>/target/debug/deps" "-L" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib" "-L" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib" "-L" "/Users/<my_user>/lib" "-L" "/usr/local/lib" "-L" "/usr/lib" "-L" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/<my_user>/<project>/target/debug/deps/libodbc-cfaeb7960856e69f.rlib" "/Users/<my_user>/<project>/target/debug/deps/libencoding_rs-2b35bc34cb8581ab.rlib" "/Users/<my_user>/<project>/target/debug/deps/libodbc_safe-9332b0a0585254e9.rlib" "/Users/<my_user>/<project>/target/debug/deps/libodbc_sys-93836ed7809c42ea.rlib" "/Users/<my_user>/<project>/target/debug/deps/liblog-e6341d4b68b4c0d2.rlib" "/Users/<my_user>/<project>/target/debug/deps/libcfg_if-a26a8e1aed04c8f0.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-cd43daae2cf7ddf1.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-8db2c641f3653a71.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-028605a5a8e4ba77.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-d8c165584b999613.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace-8ca59077c26b8378.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace_sys-9e5cb6a845ac1bcb.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-428f6f0ce2c8cd70.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-5b4e5f1e334da9a7.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-0c3a77eecc027943.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-5ff1b410a39476d9.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-bc9ef7c32fbaa74f.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-3ee6ce2ac9d08f55.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-9b01ec0dd7c68c5f.rlib" "/Users/<my_user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-dae0483206048e13.rlib" "-lodbc" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: warning: directory not found for option '-L/Users/<my_user>/lib'
          ld: library not found for -lodbc
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: could not compile <project>.

To learn more, run the command again with --verbose.

Minimum repro main.rs

extern crate odbc;

fn main(){

}`

Minimum repro Cargo.toml

`[package]
name = "<project>"
version = "0.1.0"
authors = ["<me>"]
edition = "2018"

[dependencies]
odbc = "0.14.0"`

OSX Version = 10.14.6
Rustc Version = rustc 1.40.0-nightly (1423bec54 2019-11-05)
(it's nightly because the rest of the project has deps that need nightly, but I'm able to reproduce the error in stable as well)
Cargo Version = cargo 1.40.0-nightly (5da4b4d47 2019-10-28)

**Comment by Koka** [comment]
Do you have unixODBC installed?

**Comment by jrsmith17** [comment]
I did not previously have unixODBC installed. Installing it resolved my issue.

You can make this as closed, but I did have two followup questions:

1) I didn't see this listed in the README as a dependency. Should it be? Or is this something people more familiar with raw ODBC connections just know to install?
2) Is this a dependency for all *nix based systems?

**Comment by Koka** [comment]
If you want to use ODBC you'll need odbc driver manager like unixODBC on *nix systems or MS ODBC on windows
