### ISSUE TITLE
parameter binding problem(Is this dangling pointer?)

### ISSUE THREAD

**Issue by nao-kobayashi** [Koka/odbc-rs#128]
Hi, I wrote following code.
"params" is a values of the query parameter.
When I set japanese text into params, duplicate value used in SQL.

I think String.value_ptr sometimes return duplicate addresses in the bind_parameter function.
For example, I set 10 japanese words into params Vector.
Some value is duplicated.
(I paste println results of String.value_ptr later.)
I think it may only happen in the case of SJIS or multibyte.

I am using SQLServer2016 and collate is Japanese_CI_AS.
I created ODBC environment as create_environment_v3_with_os_db_encoding("utf8", "sjis").
Rust's version is 1.39.0 and MSVC toolchain.

Please check it, thank you.

```
pub fn query<T>(
    &self,
    sql: &str,
    params: Vec<String>,
    converter: impl Fn(Vec<Option<String>>) -> T,
) -> Result<Vec<T>, Box<dyn Error>> {

    let mut conn = self.get_connection();
    let stmt = Statement::with_parent(&conn)?;
    let mut prepare_stmt = stmt.prepare(sql)?;
    prepare_stmt = prepare_stmt.reset_parameters()?;

    for (i, p) in params.iter().enumerate() {
        //I will write results of println! below.
        println!("value={} {:?}", p, (*p).value_ptr());
        prepare_stmt = prepare_stmt.bind_parameter((i + 1) as u16, p)?;
    }

    let mut query_result = Vec::new();
    if let Data(mut data) = prepare_stmt.execute()? {
        let columns = data.num_result_cols()? as u16;
        while let Some(mut cursor) = data.fetch()? {
            let mut row = Vec::new();
            for i in 1..=columns {
                row.push(cursor.get_data::<String>(i)?);
            }
            query_result.push(converter(row));
        }

        data.close_cursor()?;
    }

    conn.commit()?;
    Ok(query_result)
}
```

***** println results ************
//println!("value={} {:?}", p, (*p).value_ptr());
some value_ptr's results are duplicated!!!

value=あ 0x1c5f133cc50
value=い 0x1c5f133cbb0 <- duplicate case 1
value=う 0x1c5f133ca30 <- duplicate case 2
value=え 0x1c5f133cbb0 <- duplicate case 1
value=お 0x1c5f133ccf0
value=か 0x1c5f133ca30 <- duplicate case 2
value=き 0x1c5f133ca30 <- duplicate case 2
value=く 0x1c5f133ceb0 <- duplicate case 3
value=け 0x1c5f133ceb0 <- duplicate case 3
value=こ 0x1c5f133cbb0 <- duplicate case 1

**Comment by nao-kobayashi** [comment]
I think value_ptr method in String or &str may returns dangling pointer.
This is implementation of value_ptr method.
`unsafe { ::environment::DB_ENCODING }.encode(&self).0.as_ptr() as *const Self as ffi::SQLPOINTER`
Value of encode(&self).0  will be dropped when method call finish.
I think this pointer indicates invalid address.
Am I misunderstand?
(I changed the title of this issue  because it is not related to sjis.)

**Comment by Koka** [comment]
Thanks @nao-kobayashi 
It definitely looks like a dangling pointer, unfortunately I have no free time to fix this.
As always, I'll gladly accept any pull request that can help

**Comment by nao-kobayashi** [comment]
Thank you for your reply.
I am going to fix.

**Comment by Koka** [comment]
Should be fixed now
