### ISSUE TITLE
odbc v0.13.0 does not compile any more

### ISSUE THREAD

**Issue by jpastuszek** [Koka/odbc-rs#132]
Test project:
```
[package]
name = "odbc-test"
version = "0.1.0"
edition = "2018"

[dependencies]
odbc = "0.13.0"
```

Build fails but it was working before incompatible `odbc-safe` update:
```
$ cargo check
   Compiling odbc-sys v0.8.2
   Compiling odbc-sys v0.6.3
   Compiling log v0.4.8
    Checking cfg-if v0.1.10
    Checking odbc-safe v0.4.2
    Checking odbc v0.13.0
error[E0107]: wrong number of type arguments: expected 1, found 0
 --> /home/kazuya/.cargo/registry/src/github.com-1ecc6299db9ec823/odbc-0.13.0/src/connection.rs:7:11
  |
7 |     safe: safe::Connection<'env>,
  |           ^^^^^^^^^^^^^^^^^^^^^^ expected 1 type argument

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
error: could not compile `odbc`.

To learn more, run the command again with --verbose.
zsh: exit 101   cargo check
```

This breaks my crate `odbc-iter` that uses this particular version.
Is it possible for you to yank responsible crate so the project adheres to SemVer again, please?
Should `odbc-safe` version `v0.4.2` be yanked and re-released as `v0.5.0`? 

Otherwise I don't know how to fix my projects without updating to latest `odbc` version.

**Comment by jpastuszek** [comment]
This propagates to all my crates based on odbc v0.13.0... I cannot publish or install any of them any more. I would happily roll forward but it looks like a bit of a change for my `odbc-iter` crate that I am not ready to tackle right now.
Any chance to get this resolved, please?

**Comment by Koka** [comment]
Hey @jpastuszek sorry to hear that. I’m very short on free time last days, but I’ll try to see what we can do. Thanks for your patience

**Comment by Koka** [comment]
Ok, I have yanked 0.4.2 - hope this helps
