### ISSUE TITLE
Panic when Reading table from DB2 Driver

### ISSUE THREAD

**Issue by cetra3** [Koka/odbc-rs#134]
I'm hitting the following panic which I think relates to some DB2 related weirdness.  I have a feeling it's returning no value for a column row.

Happy to submit a PR if someone can point me in the direction of where it possibly might be an issue:

```
thread 'tokio-runtime-worker-0' panicked at 'no more data but indicatior outside of data buffer', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/odbc-0.14.0/src/statement/output.rs:69:21
```

This relates to the following line:

https://github.com/Koka/odbc-rs/blob/97bdbe7555c86b975e902211d810c9b823017062/src/statement/output.rs#L69

**Comment by Koka** [comment]
Hello, if I remember well this assertion was added by @jpastuszek - may be he can help with some advice?

**Comment by jpastuszek** [comment]
This assert is there to signal a situation in witch the driver finished providing data (SQL_SUCCESS) but yet it indicates that there should be more data than could fit in the buffer. So the data you get would be truncated as it does not fit in the buffer but yet the driver is done providing it.

This is my understanding of
https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdata-function?view=sql-server-ver15
but this call is very nuanced so I may be wrong about this.

What you can try is:
* perhaps DB2 has some minimum buffer size assumption for particular types or in some context and the get call needs to finish in one go or you get data truncated - try increasing default buffer size and see if you will get to this situation even if you query more data than that default size: https://github.com/Koka/odbc-rs/blob/70d4fb2189a45adc4e5a43dd4295fa18303cd737/src/statement/mod.rs#L201
* assume that more data will be provided even though SQL_SUCCESS was returned - so resize buffer and call again as in case of SQL_SUCCESS_WITH_INFO - and see what happens
* assume that indicator is wrong and that data fit the buffer exactly - so convert the whole buffer - this can lead to data truncation so you would need to experiment and see what if you get all the data or if it is truncated
* ?

**Comment by jpastuszek** [comment]
In the doc they say that `If the column data is larger than the maximum number of bytes that you specified for SQL_ATTR_MAX_LENGTH, SQL_SUCCESS is returned. When you specify a maximum length, DB2 ODBC returns the length you specify, not the actual length, for the pcbValue argument.`. So if you would set that attribute then this behavior would be expected and data should be truncated - so perhaps we should just let it be truncated in this case - so remove the assert and if `start_pos + indicator as usize <= buffer.len()` than convert the whole buffer as is?

**Comment by cetra3** [comment]
@jpastuszek Apologies for taking a while to get back to you.  It looks like the size is wrong for the `indicator` variable.  I have printed out the values of each and Indicator is equal to `4294967295` before panicking.

```
Start Pos: 0, Indicator: 4294967295, Buffer Len: 512,
```

As you can see it looks like a i32 `-1`, which is  `SQL_NULL_DATA`.

From the [IBM doc](https://www.ibm.com/support/knowledgecenter/SSEPEK_11.0.0/odbc/src/tpc/db2z_fngetdata.html) It looks like it may return either depending on what application mode is running:

```
SQLRETURN   SQLGetData       (SQLHSTMT          hstmt,
                              SQLUSMALLINT      icol,
                              SQLSMALLINT       fCType,
                              SQLPOINTER        rgbValue,
                              SQLINTEGER        cbValueMax,
                              SQLINTEGER FAR   *pcbValue);
```

There is a footnote on that page:

```
For 64-bit applications, the data type SQLINTEGER, which was used in previous versions of DB2, is still valid. However, for maximum application portability, using SQLLEN is recommended.
```

I'm not really sure how to fix this correctly, but reading the doco says it could be either 32 or 64 bit.  The DB2 driver I'm using is 64 bit (`v11.1.4fp4a_linuxx64_odbc_cli`).

The following change works, but not sure on its validity:

```rust
if indicator == ffi::SQL_NULL_DATA || (indicator as i32) == ffi::SQL_NULL_DATA as i32 {
```

**Comment by jpastuszek** [comment]
So this looks like a type/arch mismatch. While this workaround won't hurt, there may be more issues if this types are different (e.g. `#define  SQL_DATA_AT_EXEC    -2` is another value that would be affected). Binding parameters or other sending data calls may have similar issue.
Also I guess it would be better to define `SQL_NULL_DATA_I32: i32 = -1` for this workaround to be more clear.

**Comment by cetra3** [comment]
I am assuming this is a bug in the driver itself.  I'm happy to leave my branch active rather than make changes to the main `odbc-rs` crate as it would be too messy.  Maybe IBM will release a fix later on.. 😐
