### ISSUE TITLE
Invalid handle panic due to connection dropped before statement

### ISSUE THREAD

**Issue by jpastuszek** [Koka/odbc-rs#136]
Currently, it is possible to use the library incorrectly so that `Connection` object is dropped before `Statement` (or any derivative) leading to panic on `SQLFreeHandle` returning "invalid handle" error.

I have created a simplified reproduction of the issue in this Gist:

https://gist.github.com/jpastuszek/0471b276e6ec4fe187c4731b1581a303

Looks like what is happening is that:
* when `Statement` is part of temp variable and the Rust compiler will drop stack variables first (before temp), so if `Connection` is part of the stack it will get dropped before temp variable holding `Statement` is;
* the code using temp variable would be rejected by the compiler if `Statement` was implementing `Drop`; for some reason, `Raii` implementing `Drop` is not linked to 'con lifetime in the `parent` `PhantomData` of `Statement`;
* if I used explicit stack variable to hold object containing `Statement` this becomes valid as local variables are dropped in order;
* the problem is that compiler does not reject version with temp variable as invalid ("dropped here while still borrowed").

There are two ways to fix this:
* `impl Drop` for `Statement` which will force the compiler to consider that there is a function call (`drop()`) with `'con` lifetime running after `Connection` stack variable was dropped - code rejected: see: https://github.com/Koka/odbc-rs/compare/0.13.0...jpastuszek:statement_drop_0.13.0
* move `PhantomData<'con'>` to `Raii` and this way linking `'con` lifetime with `Drop` implementation already present on `Raii`, see: https://github.com/Koka/odbc-rs/compare/0.13.0...jpastuszek:raii_phantom_0.13.0?expand=1

I think the second option is way more elegant and correct. I have only tested compilation with these changes so they may be invalid.

Here is my initial investigation ticker:
https://github.com/jpastuszek/odbc-iter/issues/3

Note that I have run into this issue second time in my code base, the workaround was to explicitly add `Drop` impl for structs containing `Statement` so this is not an obvious flaw but it does happen.

Also I am not sure why the Rust compiler behaves this way: why temp variables are dropped after local stack variables and why `Raii` `Drop` is not linked with `PhantoData<'con>` lifetime in current implementation - perhaps it would be worth consulting with some Rust guru.

**Comment by Koka** [comment]
Great finding @jpastuszek ! Do you want to propose pull request?
