### ISSUE TITLE
lib build failed

### ISSUE THREAD

**Issue by pawelpn** [Koka/odbc-rs#161]
After I update rust to version.

cargo --version
cargo 1.50.0 (f04e7fab7 2021-02-04)

rustup --version
rustup 1.23.1 (3df2264a9 2020-11-30)

Library odbc = "0.17.0" not compiling now. Got an error:

error[E0277]: the trait bound `V: Version` is not satisfied
  --> C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\odbc-0.17.0\src\environment\mod.rs:19:11
   |
19 |     safe: safe::Environment<V>,
   |           ^^^^^^^^^^^^^^^^^^^^ the trait `Version` is not implemented for `V`
   |

**Comment by pacman82** [comment]
See #160 . To fix our build Pin odbc-safe to 0.5.0.

**Comment by pawelpn** [comment]
solved, thanks
