### ISSUE TITLE
get_data fetches garbage on linux

### ISSUE THREAD

**Issue by pacman82** [Koka/odbc-rs#23]
> One "error" was that if I did a SELECT on one column, the data didn't seems to match the real data but it looked familiar (like if I had parts of the data or if the rows weren't spitted correctly).

I've been able to reproduce this behavior. Sadly it only occurs on Linux using unix_odbc. I do not get this locally on my windows machine. Luckily for now I did not require MS SQL to reproduce this SQLite is quite enough. Now I only have to fix it...

**Comment by Koka** [comment]
@pacman82 It was totally fine in my initial experiment with postgresql on linux (with autogenerated ffi mappings). May be we should try again and search for differences in code

**Comment by pacman82** [comment]
If you want to join in the fun: I have [a reproducing test](https://github.com/pacman82/odbc-rs/blob/query_test/tests/libs.rs#L75). For additional WTF remove the `println` from the test and see it pass on stable but fail on beta and nightly.

This is what I found out so far:
* The first four bytes of the retrieved strings are always zero. The rest is fine.
* Shifting the passed pointer passed to SQLGetData by 4 bytes into the array fixes the Bug.

**Comment by pacman82** [comment]
ok, the call to `SQLGetData` seems fine. Something immediately after it sets the first 4 Bytes of the buffer to zero, no matter what pointer has been passed to `SQLGetData`

**Comment by Koka** [comment]
Problem is fixed, but let's leave this open for further investigation

**Comment by pacman82** [comment]
[This reddit thread](https://www.reddit.com/r/rust/comments/60b4v5/can_anyone_help_me_identify_what_i_did_wrong_in/?st=j0hcsv7z&sh=f900870e) helped finding the cause. The definition of `SQLLEN` had been 32 Bit on 64 Bit linux platforms. I fixed this Bug in the odbc-sys crate.
