### ISSUE TITLE
AppVeyor build integration and Windows builds

### ISSUE THREAD

**Issue by Koka** [Koka/odbc-rs#25]
We could add https://www.appveyor.com/ build to ensure this crate works well on windows environments (and add some tests for windows specific databases like MSSQL too)

**Comment by pacman82** [comment]
Just used [this repository](https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml) to enable AppVeyor for odbc-ffi. Works like a charm!

**Comment by Koka** [comment]
I've did initial appveyor setup, but it has some problems linking on i686 arch. Will investigate later.

**Comment by pacman82** [comment]
These are probably the [the same linking errors](https://ci.appveyor.com/project/pacman82/odbc-ffi/build/job/641p4j68hub92q1s) `odbc-sys` has linking on 32 Bit platforms. I do not yet know what causes this. Maybe he is trying to use the 64Bit `odbc32.dll`? I'd say `odbc-rs` should just go ahead with the x86_64 toolchain for now and let's debug the 32Bit build using `odbc-sys`.
