### ISSUE TITLE
user extensible value decoding

### ISSUE THREAD

**Issue by jlgale** [Koka/odbc-rs#39]
The `Output` trait describes how a rust type can be derived from a query result value. However, it can only be implemented within the library itself.

This means, for example, that I can't query a datetime directly into a rust datetime value unless this library implements it. The postgres crate (https://github.com/sfackler/rust-postgres) does nice job with this, providing a trait that users can implement themselves (assuming they understand the postgres value encoding)

**Comment by jlgale** [comment]
I guess that what I really want is datetime decoding, but if this was fixed I could add it myself. :)

**Comment by Koka** [comment]
@jlgale Hello, could you please check example code at [examples/custom_get_data.rs](https://github.com/Koka/odbc-rs/pull/40/files#diff-63083071fae37cbd1121b991193bcb39) ? 

Does this resolve problem you've mentioned in this issue?

**Comment by jlgale** [comment]
Yeah, it appears so. It's your library and but as a user my feedback is that I'm surprised I would have to use `unsafe` to functions to decode a value. I'm also surprised that the `Raii` container is exposed to here. It's also a little odd that the buffer is mutable?

**Comment by Koka** [comment]
@jlgale Of course it still needs refactoring, I just want to be sure I'm moving right direction.

**Comment by Koka** [comment]
@jlgale check example in 0.7.0 release - it should be much better now

**Comment by jlgale** [comment]
Thanks, I'll try it
