### ISSUE TITLE
`get_data` on large string field results in `None`

### ISSUE THREAD

**Issue by cristianberneanu** [Koka/odbc-rs#64]
Hi,

I am trying to use the `odbc` crate to process some data in a SQL Server database.
During processing, I get `null` values for some of the string fields that have a large amount of content in them. Is that a known bug? If yes, is there some workaround that I can use?

Thanks.

**Comment by Koka** [comment]
Hi @cristianberneanu, I believe that somehow related to https://github.com/Koka/odbc-rs/issues/41 
The only workaround you can use for now is to implement this column handling logic yourself using underlying low level odbc-safe / odbc-sys crates

**Comment by cristianberneanu** [comment]
OK, thanks for the info, I will look into doing that.
