### ISSUE TITLE
Example on crates.io is out of date.

### ISSUE THREAD

**Issue by mehemken** [Koka/odbc-rs#67]
New Rust user coming from Python. I need a Rust program that speaks `odbc` and I stumbled upon this project. However, I think [the example](https://crates.io/crates/odbc) is out of date. I'm new to Rust so I don't think I can contribute to the code, but I'd love to help with the Documentation.

You need any help with that?

**Comment by Koka** [comment]
Hi @mehemken I very appreciate any help with this project, thanks!

**Comment by Koka** [comment]
@mehemken I've fixed example in README, and it seems to work OK: https://monosnap.com/file/Q6wfPue09m7uczRe38DFzBYtR3hp9A

BTW you can always find working examples in `examples` directory of this repo

**Comment by mehemken** [comment]
Ok I'll give it a shot. Thanks @Koka
