### ISSUE TITLE
How to treat SUCCESS_WITH_INFO in a high level abstraction of odbc?

### ISSUE THREAD

**Issue by pacman82** [Koka/odbc-rs#7]
For the low level stuff SUCCESS_WITH_INFO mostly happens if a buffer is truncated, which we can avoid entirely. Actually executing SQL Statements however is an entirely different matter. How do we handle ODBC notion of warnings (SQL_SUCCESS_WITH_INFO) with idomatic error handling in RUST which only knows `Ok` and `Error`?

**Comment by Koka** [comment]
@pacman82  I've seen this https://github.com/canndrew/w_result - may be we should implement something like this or use it directly if it's appropriate

**Comment by pacman82** [comment]
@Koka sorry for the long response time, took an extended vacation over the holidays. Back to the topic at hand: We could use this crate, but then the user would have a hard time to opt out of fetching these warnings (and allocating these strings and so on...). Currently I'm thinking more along the lines of indicating the presence of warnings (or infos) with the result enum and let the user fetch the messages if she wants to do so. This would mimic the behaviour of the underlying C-Library.

**Comment by Koka** [comment]
@pacman82 Sounds reasonable.

**Comment by pacman82** [comment]
For now let's log these as warnings: #19

**Comment by Koka** [comment]
I think it's ok
