### ISSUE TITLE
iODBC Driver Manager support

### ISSUE THREAD

**Issue by paperplanes53** [Koka/odbc-rs#78]
I am trying to connect to a sqlite3 database to query a table. In my project, the connection string gives me the error 'Diagnostics returned error for record number 2. Record numbers have to be at least 1.'  

I decided to download the crate individually to see if I could run test examples and figure out what is wrong with my code. None of the tests pass. 

My output is below: 
[cargo_test_output.txt](https://github.com/Koka/odbc-rs/files/2149460/cargo_test_output.txt)

Also, is there a list of dependencies need for this repo? I got a linker error until I used "brew install libiodbc".

**Comment by Koka** [comment]
Actually, I've never tried this crate with iodbc, but should work too. 
Can you please add more details on your environment?

Failing tests can be related not only to the crate itself, but also to environment, ODBC driver manager or driver and datasource setup.

The only native dependence of this crate is odbc driver manager. It should be already installed on Windows and for Linux and Mac you need to install it manually (like UnixODBC or iodbc)

**Comment by paperplanes53** [comment]
I am using rustc 1.28.0-nightly (e3bf634e0 2018-06-28) now on a Mac. I am also using Homebrew 1.6.9. I uninstalled libiodbc. I have cmake version 3.11.1.

I looked at travis.yml again and noticed allow_failures. Is Nightly supported for this repo? 

Doing brew search odbc shows I could use libiodbc, psqlodbc, unixodbc, sqliteodbc, and 
mariadb-connector-odbc. 

Doing brew search binutils shows I could use arm-linux-gnueabihf-binutils or binutils.
Brew search does not have results for libdw-dev and libcurl4. Brew search libelf only gives libelf.

If needed, i'll manually install the packages brew doesn't have.

I am using the attached script, which uses all of the repo example script. I enter the connection string "dsn=LocalDataSource;Uid=;Pwd=;" when prompted and the SQL query "SELECT * FROM my_table_name" when prompted. I did not make a Travis folder.
project 
   | src 
        | bin 
            | obdc_test_file.rs (using for script)
            | other files
        | sample_folder
             | odbc.ini    (using this, attached below)
             | bar.sqlite  (using this database)
             | other files 
        | other folders
        | main.rs and other files
   | target and other folders
   | Cargo.toml and other files

Maybe my problem is that the contents of obdc.ini file ([LocalDataSource]...) are not visible to other files like odbc_test_file.rs.

Thank you for any insights you may have. 

[odbc.ini.zip](https://github.com/Koka/odbc-rs/files/2155215/odbc.ini.zip)

**Comment by ccakes** [comment]
Just an additional datapoint - on macOS 10.12 linking against libiodbc results in all tests failing, removed that and retried with unixodbc and all works fine.

I didn't try installing iODBC Driver Manager like OP did though.

**Comment by paperplanes53** [comment]
I removed iODBC Driver Manager and now only have unixodbc. Thank you @ccakes

**Comment by Koka** [comment]
So looks like iODBC doesn't work well with this crate. I'm renaming this issue to iODBC Driver Manager support request
