### ISSUE TITLE
How to Get Rows Updated when Running Insert Command

### ISSUE THREAD

**Issue by vnnv01** [Koka/odbc-rs#80]
I am trying to insert a record in to table using select statement and I want to know how many records inserted. I am not able to get the results using cursor. Is there any other ways to get number of records affected in ODBC

**Comment by Koka** [comment]
Thanks for your question. You might find this article helpful: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/determining-the-number-of-affected-rows?view=sql-server-2017

You could use SQLRowCount function to retrieve affected record count. 

Unfortunately, looks like it has no FFI wrapper in odbc-sys crate yet, so you could either wait for implemrntation or contribute corresponding PR yourself.

**Comment by Koka** [comment]
It will not appear automatically in this crate, but will be quite easy to add it here if it will be added to odbc-sys

**Comment by Koka** [comment]
Finally, I had a minute of free time to release this feature as 0.9.12 (although not using odbc-safe interaction, but directly using odbc-sys). You could find usage example [here](https://github.com/Koka/odbc-rs/blob/master/examples/affected_row_count.rs)
